### ISSUE TITLE
Cannot Download on Kubuntu 23.04

### ISSUE THREAD

**Issue by ZaxLofful** [torproject/torbrowser-launcher#718]
- [X] I am using the latest version and the problem persists.

I am using the version from the KDE Discover Flatpak browser and was able to install the version from Flathub with no problem, but I still get the 404 error when attempting to install the Tor Browser.

Are there more logs you would like me to provide?

**Comment by boklm** [comment]
Can you provide the URL that results in a 404 error?

**Comment by yaourtiere** [comment]
The package in Flathub seems to use the the [v0.3.6 release of this repo](https://github.com/flathub/com.github.micahflee.torbrowser-launcher/blob/e5bd7126bc32a82b29a610d9d9f05674f73227d3/com.github.micahflee.torbrowser-launcher.yaml#L206C3-L206C3)

If packagers wants to patch this, they should use the git version (or apply a hot patch as suggested in https://github.com/torproject/torbrowser-launcher/issues/715#issuecomment-1761305048). Otherwise we have to wait for a new release of the program.

[An issue have been submitted](https://gitlab.torproject.org/tpo/applications/torbrowser-launcher/-/issues/5) on the main forge, demanding a new release.

**Comment by AsciiWolf** [comment]
@ZaxLofful Could you retry the download now? I have patched the Flatpak probably shortly after your ticket was created. :-)

**Comment by ZaxLofful** [comment]
Yeah it works now
